[font]
size = 13

[font.bold]
family = "FiraMono"
style = "Bold"

[font.italic]
family = "FiraMono"
style = "Italic"

[font.normal]
family = "FiraMono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Alt|Shift"

[window]
opacity = 0.95
dynamic_title = true

[colors.primary]
foreground = "#d3b58d"
background = "#062625"
